### PR TITLE
add meetup ppt

### PR DESCRIPTION
**Pull request by duglin**
ping @mhbauer @brahmaroutu  new home

Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by duglin** [comment]
reopened to kick off travis

**Comment by duglin** [comment]
don't merge until I get the travis stuff tested and working

**Comment by duglin** [comment]
ok travis is happy now

**Comment by duglin** [comment]
all set

**Comment by MHBauer** [comment]
PR should be split in two. Seems to contain some random script in addition to ppt.

**Pull request merged**
