### PR TITLE
first round of deletions

### PR DESCRIPTION
**Pull request by MHBauer**
too advanced for a 101 class and outside of scope of existing class.

### CODE REVIEW

**Comment by duglin** [comment]
Let's discuss this on Friday

**Comment by MHBauer** [comment]
Seems like I missed this meeting. What was the determination?

**Comment by MHBauer** [comment]
updated to pass the linker checker

**Comment by MHBauer** [comment]
@duglin @jkomg @nimbcode If I am going to own this, I need access to merge things.

**Comment by duglin** [comment]
LGTM

**Pull request merged**
